# Generated by Django 2.2.28 on 2023-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medic_quty',
            field=models.FloatField(default=1, help_text='Select Qauntity of medicine', max_length=1000),
        ),
    ]
