# Generated by Django 2.2.28 on 2023-02-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_medicine_medic_quty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medic_copy',
            options={'permissions': (('can_create_med', 'Set create by user'),)},
        ),
    ]
