# Generated by Django 2.2.28 on 2023-02-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20230213_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic_copy',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='medic_copy',
            name='medname',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='diseases_name',
        ),
        migrations.DeleteModel(
            name='diseases',
        ),
        migrations.DeleteModel(
            name='medic_copy',
        ),
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
