# Generated by Django 2.2.28 on 2023-02-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='user',
            new_name='main_user',
        ),
    ]
