# Generated by Django 2.2.28 on 2023-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20230214_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.IntegerField(default=0, help_text='Medicine Id', primary_key=True, serialize=False),
        ),
    ]
