# Generated by Django 2.2.28 on 2023-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20230223_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.AutoField(help_text='Medicine Id', primary_key=True, serialize=False),
        ),
    ]
